# Generated by Django 5.0.4 on 2024-04-23 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_alter_camp_details_createdby'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('appointment_number', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('appointment_date', models.DateField()),
                ('camp_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administration.camp_details')),
                ('user_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
