# Generated by Django 5.0.4 on 2024-04-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_alter_appointment_appointment_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='token_no',
            field=models.IntegerField(null=True),
        ),
    ]
